# Generated by Django 5.1 on 2024-10-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Remarks',
        ),
    ]
