# Generated by Django 5.1 on 2024-10-23 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_submission_remarks_delete_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userannouncementstatus',
            name='announcement',
        ),
        migrations.RemoveField(
            model_name='userannouncementstatus',
            name='user',
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.DeleteModel(
            name='UserAnnouncementStatus',
        ),
    ]
