# Generated by Django 5.1 on 2024-10-24 10:34

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_userannouncementstatus_announcement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcomplaints',
            name='complaint',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
